[pytest]
addopts = -q --tb=short
testpaths = tests
pythonpath = . ..
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning:pandas
    ignore::DeprecationWarning:sqlalchemy
    ignore::DeprecationWarning:fastapi
    ignore::DeprecationWarning:starlette
    ignore::sqlalchemy.exc.MovedIn20Warning
