-- Migration: 002_workspace_schema.sql
-- Description: Add projects, enhanced documents, impersonation logs for client workspace system
-- Date: 2026-03-27

-- Enable UUID extension if not exists
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- PROJECTS TABLE
-- One client can have many projects
-- ============================================================================
CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    client_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    -- Project info
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'active',  -- active, completed, on_hold, archived
    phase VARCHAR(50) DEFAULT 'discovery', -- discovery, planning, execution, review, completed
    
    -- Timeline
    start_date TIMESTAMP WITH TIME ZONE,
    deadline TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    
    -- Financials
    contract_value NUMERIC(12,2) DEFAULT 0,
    
    -- Dashboard embed (per-project dashboards)
    tableau_embed_html TEXT,
    tableau_embed_type VARCHAR(50) DEFAULT 'dashboard',
    tableau_open_url TEXT,
    
    -- Soft delete
    archived_at TIMESTAMP WITH TIME ZONE,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_projects_client_id ON projects(client_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);

-- ============================================================================
-- DOCUMENTS TABLE UPDATES
-- Add project linking, visibility, document types, soft delete
-- ============================================================================

-- Add project_id column
ALTER TABLE documents ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES projects(id) ON DELETE SET NULL;

-- Add visibility: admin_only, internal, client_visible
ALTER TABLE documents ADD COLUMN IF NOT EXISTS visibility VARCHAR(50) DEFAULT 'client_visible';

-- Add document type: proposal, contract, invoice, report, deliverable, data, other
ALTER TABLE documents ADD COLUMN IF NOT EXISTS document_type VARCHAR(50) DEFAULT 'deliverable';

-- Track if generated by system (report generator, etc.)
ALTER TABLE documents ADD COLUMN IF NOT EXISTS generated_by VARCHAR(100);

-- Soft delete
ALTER TABLE documents ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE;

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_documents_project_id ON documents(project_id);
CREATE INDEX IF NOT EXISTS idx_documents_visibility ON documents(visibility);
CREATE INDEX IF NOT EXISTS idx_documents_document_type ON documents(document_type);

-- ============================================================================
-- UPLOADS TABLE UPDATES
-- Add project linking, refresh workflow tracking
-- ============================================================================

-- Add project_id column
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES projects(id) ON DELETE SET NULL;

-- Dashboard refresh workflow
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS refresh_status VARCHAR(50) DEFAULT 'none'; -- none, pending, processing, completed, failed
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS refresh_started_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS refresh_completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS refresh_error TEXT;

-- Add index
CREATE INDEX IF NOT EXISTS idx_uploads_project_id ON uploads(project_id);

-- ============================================================================
-- INVOICES TABLE UPDATES
-- Add project linking, QuickBooks integration fields
-- ============================================================================

-- Add project_id column
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES projects(id) ON DELETE SET NULL;

-- QuickBooks integration
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS quickbooks_invoice_id VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS quickbooks_customer_id VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS quickbooks_payment_url TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS quickbooks_synced_at TIMESTAMP WITH TIME ZONE;

-- Soft delete
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE;

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_invoices_project_id ON invoices(project_id);
CREATE INDEX IF NOT EXISTS idx_invoices_quickbooks_invoice_id ON invoices(quickbooks_invoice_id);

-- ============================================================================
-- IMPERSONATION LOGS TABLE
-- Audit trail for admin viewing client portals
-- ============================================================================
CREATE TABLE IF NOT EXISTS impersonation_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    admin_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    -- Action details
    action VARCHAR(100) NOT NULL,  -- start_session, end_session, page_view, action
    page_path TEXT,
    action_details JSONB,
    
    -- Request info
    ip_address VARCHAR(45),
    user_agent TEXT,
    
    -- Timestamp
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_impersonation_logs_admin_id ON impersonation_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_impersonation_logs_client_id ON impersonation_logs(client_id);
CREATE INDEX IF NOT EXISTS idx_impersonation_logs_created_at ON impersonation_logs(created_at);

-- ============================================================================
-- ENHANCED TASKS TABLE UPDATES
-- Link tasks to projects
-- ============================================================================
ALTER TABLE enhanced_tasks ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES projects(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_enhanced_tasks_project_id ON enhanced_tasks(project_id);

-- ============================================================================
-- UPDATE TRIGGERS
-- ============================================================================

-- Projects updated_at trigger
CREATE OR REPLACE FUNCTION update_projects_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_projects_updated_at ON projects;
CREATE TRIGGER update_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW
    EXECUTE FUNCTION update_projects_updated_at();

-- ============================================================================
-- COMMENTS
-- ============================================================================
COMMENT ON TABLE projects IS 'Client projects - one client can have many projects';
COMMENT ON TABLE impersonation_logs IS 'Audit log for admin impersonation of client portal views';
COMMENT ON COLUMN documents.visibility IS 'admin_only: only admins see, internal: admins + internal team, client_visible: client can see';
COMMENT ON COLUMN documents.document_type IS 'proposal, contract, invoice, report, deliverable, data, other';
COMMENT ON COLUMN uploads.refresh_status IS 'Dashboard refresh workflow status: none, pending, processing, completed, failed';
