"""
AI-assisted dispatch resource predictor — R&D prototype.

From a 911 chief complaint / call note (free text), predict the likely resource
need (ALS vs BLS), the acuity, and the time-critical interventions the crew may
need (airway, hemorrhage control, CPR, transfusion, etc.). This is DECISION
SUPPORT for a dispatcher — a human always makes the final call — and an R&D
prototype, not a validated medical device.

Primary path uses Claude (same httpx pattern as ems_ai_insights_service); a
deterministic keyword heuristic is the fallback when no API key is configured, so
the tool always returns something explainable. No PHI is required or stored.
"""
import logging
import re
from typing import Any, Dict, List

import httpx

from .ems_ai_insights_service import _ANTHROPIC_URL, _MODEL, _api_key, _parse_json

logger = logging.getLogger(__name__)

_DISCLAIMER = (
    "Decision support only — an R&D prototype, not a medical device or medical direction. "
    "A qualified dispatcher/clinician makes the final resource decision. Do not enter patient-identifying information."
)

# Interventions the model chooses from, so output stays consistent.
_INTERVENTIONS = [
    "Airway management", "Assisted ventilation / high-flow oxygen", "CPR / defibrillation",
    "Cardiac monitoring / 12-lead ECG", "Hemorrhage control", "IV access / fluid resuscitation",
    "Medication administration", "Possible blood transfusion (trauma center)",
    "Spinal motion restriction", "Advanced pain management", "Childbirth / neonatal support",
]

_SYSTEM = (
    "You are an EMS dispatch decision-support assistant. Given a 911 chief complaint or call note, "
    "estimate the resources an EMS response is likely to need. You are NOT diagnosing, providing medical "
    "direction, or making the final decision — a human dispatcher does. Be conservative: when the text is "
    "ambiguous or contains red flags, lean toward the higher level of care (ALS) and say why.\n\n"
    "Assess:\n"
    "- level: 'ALS' or 'BLS' (advanced vs basic life support likely needed)\n"
    "- acuity: 'high', 'moderate', or 'low'\n"
    "- interventions: which of these are plausibly needed, each with likelihood 'high'|'moderate'|'low'. "
    "Choose ONLY from this list, using the exact names: " + "; ".join(_INTERVENTIONS) + "\n"
    "- red_flags: short phrases from the text that drive urgency (e.g. 'not breathing', 'chest pain + diaphoresis')\n"
    "- rationale: 2-3 plain sentences a dispatcher can read quickly\n"
    "- recommended_response: a short dispatch suggestion (e.g. 'ALS + BLS, expedited' or 'BLS, routine')\n\n"
    "Respond with ONLY a JSON object, no prose, exactly:\n"
    '{"level":"ALS|BLS","level_note":"short","acuity":"high|moderate|low",'
    '"interventions":[{"name":"...","likelihood":"high|moderate|low"}],'
    '"red_flags":["..."],"rationale":"...","recommended_response":"..."}'
)


async def predict_dispatch(text: str) -> Dict[str, Any]:
    text = (text or "").strip()
    if len(text) < 3:
        return {"available": False, "reason": "Enter a chief complaint or call note to analyze."}

    api_key = _api_key()
    if not api_key:
        out = _heuristic_predict(text)
        out["disclaimer"] = _DISCLAIMER
        return out

    payload = {
        "model": _MODEL,
        "max_tokens": 900,
        "system": _SYSTEM,
        "messages": [{"role": "user", "content": f"911 call text:\n\"\"\"\n{text[:2000]}\n\"\"\"\n\nProduce the JSON."}],
    }
    headers = {"x-api-key": api_key, "anthropic-version": "2023-06-01", "content-type": "application/json"}
    try:
        async with httpx.AsyncClient(timeout=45.0) as client:
            resp = await client.post(_ANTHROPIC_URL, json=payload, headers=headers)
            resp.raise_for_status()
        body = resp.json()
        raw = next((b.get("text", "") for b in body.get("content", []) if b.get("type") == "text"), "")
        parsed = _parse_json(raw)
    except Exception as exc:  # noqa: BLE001
        logger.warning("dispatch-predict: LLM path failed (%s); using heuristic", exc)
        out = _heuristic_predict(text)
        out["disclaimer"] = _DISCLAIMER
        out["note"] = "Generated by the keyword fallback (AI service unavailable)."
        return out

    if not isinstance(parsed, dict) or not parsed.get("level"):
        out = _heuristic_predict(text)
        out["disclaimer"] = _DISCLAIMER
        out["note"] = "Generated by the keyword fallback (unreadable AI response)."
        return out

    level = "ALS" if str(parsed.get("level", "")).upper().startswith("ALS") else "BLS"
    acuity = str(parsed.get("acuity", "moderate")).lower()
    acuity = acuity if acuity in ("high", "moderate", "low") else "moderate"
    interventions = []
    for it in (parsed.get("interventions") or [])[:10]:
        if isinstance(it, dict) and it.get("name"):
            lk = str(it.get("likelihood", "moderate")).lower()
            interventions.append({"name": str(it["name"])[:80], "likelihood": lk if lk in ("high", "moderate", "low") else "moderate"})
    return {
        "available": True,
        "method": "ai",
        "level": level,
        "level_note": str(parsed.get("level_note", ""))[:160],
        "acuity": acuity,
        "interventions": interventions,
        "red_flags": [str(x)[:120] for x in (parsed.get("red_flags") or [])][:8],
        "rationale": str(parsed.get("rationale", ""))[:600],
        "recommended_response": str(parsed.get("recommended_response", ""))[:160],
        "disclaimer": _DISCLAIMER,
    }


# ---------------------------------------------------------------------------
# Deterministic keyword fallback
# ---------------------------------------------------------------------------
# (regex, intervention, likelihood, acuity_weight, als, red_flag_label)
_RULES = [
    (r"\b(cardiac arrest|not breathing|no pulse|cpr in progress|unresponsive and not breathing)\b", "CPR / defibrillation", "high", 3, True, "possible cardiac arrest"),
    (r"\b(chest pain|heart attack|mi\b|cardiac|palpitations|diaphore)\b", "Cardiac monitoring / 12-lead ECG", "high", 2, True, "cardiac complaint"),
    (r"\b(stroke|cva|facial droop|slurred speech|one[- ]sided weakness)\b", "IV access / fluid resuscitation", "moderate", 2, True, "possible stroke"),
    (r"\b(difficulty breathing|short(ness)? of breath|sob\b|respiratory distress|asthma|can'?t breathe|choking)\b", "Assisted ventilation / high-flow oxygen", "high", 2, True, "respiratory distress"),
    (r"\b(unconscious|unresponsive|altered mental|passed out|syncope|fainted)\b", "Airway management", "moderate", 2, True, "altered / unresponsive"),
    (r"\b(seizure|convulsion|seizing)\b", "Medication administration", "moderate", 2, True, "active seizure"),
    (r"\b(overdose|\bod\b|narcan|naloxone|poison)\b", "Medication administration", "high", 2, True, "overdose / poisoning"),
    (r"\b(allergic reaction|anaphylax|epipen|swelling of (the )?(throat|tongue))\b", "Medication administration", "high", 2, True, "allergic reaction"),
    (r"\b(gunshot|gsw|shot|stab|impaled|amputat|major bleeding|hemorrhage|arterial bleed)\b", "Hemorrhage control", "high", 3, True, "penetrating trauma / major bleeding"),
    (r"\b(mva|motor vehicle|car (crash|accident)|rollover|ejected|entrapment|head[- ]on)\b", "Spinal motion restriction", "moderate", 2, True, "motor-vehicle collision"),
    (r"\b(fall|fell)\b", "Spinal motion restriction", "low", 1, False, "fall"),
    (r"\b(diabetic|low blood sugar|hypoglyc)\b", "IV access / fluid resuscitation", "moderate", 1, True, "diabetic emergency"),
    (r"\b(labor|childbirth|contractions|water broke|delivering)\b", "Childbirth / neonatal support", "moderate", 2, True, "imminent childbirth"),
    (r"\b(severe pain|10/10 pain)\b", "Advanced pain management", "moderate", 1, False, "severe pain"),
    (r"\b(trauma|major trauma)\b", "Possible blood transfusion (trauma center)", "moderate", 2, True, "major trauma"),
]


def _heuristic_predict(text: str) -> Dict[str, Any]:
    t = " " + text.lower() + " "
    interventions: List[Dict[str, str]] = []
    seen = set()
    red_flags: List[str] = []
    acuity_score = 0
    als = False
    for pattern, name, likelihood, weight, is_als, flag in _RULES:
        if re.search(pattern, t):
            if name not in seen:
                interventions.append({"name": name, "likelihood": likelihood})
                seen.add(name)
            red_flags.append(flag)
            acuity_score += weight
            als = als or is_als

    acuity = "high" if acuity_score >= 3 else "moderate" if acuity_score >= 1 else "low"
    level = "ALS" if als else "BLS"
    if not interventions:
        interventions = [{"name": "Assisted ventilation / high-flow oxygen", "likelihood": "low"}]
        rationale = "No high-acuity keywords detected. Likely a BLS-level response, but confirm with caller interrogation."
    else:
        rationale = (
            f"Keyword screen flagged: {', '.join(sorted(set(red_flags)))}. "
            f"Leaning {level} at {acuity} acuity — verify with the caller and follow local protocol."
        )
    return {
        "available": True,
        "method": "heuristic",
        "level": level,
        "level_note": f"{level} from keyword screen" if als else "BLS from keyword screen",
        "acuity": acuity,
        "interventions": interventions[:8],
        "red_flags": sorted(set(red_flags))[:8],
        "rationale": rationale,
        "recommended_response": ("ALS + BLS, expedited" if acuity == "high" else "ALS" if level == "ALS" else "BLS, routine"),
    }
